/* export const ADD_USER="ADD_USER"
 */export const GET_ALL_USERS="GET_ALL_USERS"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER= "DELETE_USER"

export const USER_RGISTER="USER_RGISTER"
export const USER_LOGIN="USER_LOGIN"
export const USER_FAIL="USER_FAIL"
export const GET_USER="GET_USER"
export const LOG_OUT="LOG_OUT"

export const ADD_INTERVENANT="ADD_INTERVENANT"
export const GET_ALL_INTERVENANTS="GET_ALL_INTERVENANTS"
export const GET_INTERVENANT="GET_INTERVENANT"
export const UPDATE_INTERVENANT = "UPDATE_INTERVENAN"
export const DELETE_INTERVENANT = "DELETE_INTERVENANT"






